version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: uprmeals-postgres
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uprmeals-password
      POSTGRES_DB: uprmeals
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data
